/********************************************************************
*   File   : load_inst.c
*   Author : Neng-Fa ZHOU Copyright (C) 1994-2019
*   DO NOT EDIT! THIS FILE IS AUTOMATICALLY GENERATED.

* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0. If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
********************************************************************/
